apiVersion: apps/v1
kind: Deployment
metadata:
  name: acr-demo03
  labels:
    app: acr-demo03
spec:
  replicas: 2
  selector:
    matchLabels: 
     app: acr-demo03
  template:
    metadata:
      labels:
        app: acr-demo03
    spec:
      containers:
      - name: customaksnginxapp3
        image: acrdemo03.azurecr.io/customaksnginxapp3
        ports:
          - containerPort: 80
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: acr-demo03-loadbalancer-service
  labels:
    app: acr-demo03
spec: 
  selector:
    app: acr-demo03
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
