apiVersion: apps/v1
kind: Deployment
metadata:
  name: acr-demo04
  labels:
    app: acr-demo04
spec:
  replicas: 2
  selector:
    matchLabels: 
     app: acr-demo04
  template:
    metadata:
      labels:
        app: acr-demo04
    spec:
      containers:
      - name: acrdemo04
        image: acrdemo04.azurecr.io/imagedemo04tagged
        ports:
          - containerPort: 80
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: acr-demo04-loadbalancer-service
  labels:
    app: acr-demo04
spec: 
  selector:
    app: acr-demo04
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
